dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"

install:
  - pip install -e .

script:
  - py.test . --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
